name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test

      - name: Generate Changelog
        run: |
          git fetch --tags
          latest_tag=$(git tag -l | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Changelog cannot be generated."
          else
            echo "Latest tag: $latest_tag"
            echo "# Changelog:" > changelog.txt
            echo -e "Changelog:"
            git log --pretty=format:"- %s" "$latest_tag..HEAD" | tee changelog.txt
          fi

      - name: Debug
        run: cat changelog.txt

      - name: Publish
        run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          echo "version=$(cargo pkgid | cut -d# -f2 | cut '-d:' -f2)" >> $GITHUB_OUTPUT


      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          bodyFile: changelog.txt
      
